dist: xenial
language: python
cache: pip
branches:
  only:
  - master
matrix:
  include:
  - name: Wiki Build
    python: '3.6'
    env: BUILD_FOCUS=WIKI
  - name: PDF Build
    python: '3.6'
    env: BUILD_FOCUS=PDF
    addons:
      apt:
        packages:
        - texlive-full
install:
- bash _scripts/install.sh
script:
- bash _scripts/script.sh
before_deploy:
- openssl aes-256-cbc -K $encrypted_0a73d3c4e754_key -iv $encrypted_0a73d3c4e754_iv
  -in deploy_wiki.enc -out /tmp/deploy_wiki -d
- openssl aes-256-cbc -K $encrypted_0a73d3c4e754_key -iv $encrypted_0a73d3c4e754_iv
  -in deploy_site.enc -out /tmp/deploy_site -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_wiki
- chmod 600 /tmp/deploy_site
deploy:
  provider: script
  script: bash _scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
